import fs from "node:fs";
import path from "node:path";
import PDFDocument from "pdfkit";
import { db } from "../db/index.js";
import { getBillById } from "../tools/billing.js";
import { readPreference } from "../tools/preferences.js";
import { fail, type ToolResult } from "../tools/shared.js";

const INVOICE_DIR = "./data/invoices";
fs.mkdirSync(INVOICE_DIR, { recursive: true });

interface InvoiceLine {
  product_name: string;
  unit: string;
  qty: number;
  unit_price: number;
  gst_rate: number;
  hsn_code: string;
  line_subtotal: number;
  line_cgst: number;
  line_sgst: number;
  line_total: number;
}

/**
 * Renders a GST-correct tax invoice for a finalized bill as a PDF. Only
 * finalized bills can be invoiced - a draft has no legal tax event yet.
 * This is the agent's own tool output (brief hard-part #8: "generated by the
 * agent's own tools, not screenshots or plain text").
 */
export async function generateInvoicePdf(input: { billId: number }): Promise<ToolResult> {
  const bill = getBillById(input.billId);
  if (!bill) return fail(`No bill #${input.billId}.`);
  if (bill.status !== "finalized") return fail(`Bill #${input.billId} is not finalized yet - finalize it before generating an invoice.`);

  const lines = db
    .prepare(
      `SELECT bi.product_name, bi.unit, bi.qty, bi.unit_price, bi.gst_rate, p.hsn_code,
              bi.line_subtotal, bi.line_cgst, bi.line_sgst, bi.line_total
       FROM bill_items bi JOIN products p ON p.id = bi.product_id
       WHERE bi.bill_id = ?`
    )
    .all(bill.id) as InvoiceLine[];

  const shopName = readPreference("shop_name") ?? "Nebula Kirana Store";
  const shopGstin = readPreference("shop_gstin");
  const filePath = path.join(INVOICE_DIR, `invoice-${bill.id}.pdf`);

  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 40 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    doc.fontSize(18).text(shopName, { align: "left" });
    if (shopGstin) doc.fontSize(9).fillColor("#555").text(`GSTIN: ${shopGstin}`);
    doc.moveDown(0.3);
    doc.fontSize(14).fillColor("#000").text("TAX INVOICE", { align: "left" });
    doc.fontSize(9).fillColor("#555").text(`Invoice #${bill.id}   |   Date: ${bill.finalized_at}   |   Payment: ${(bill.payment_mode ?? "-").toUpperCase()}${bill.payment_ref ? " (" + bill.payment_ref + ")" : ""}`);
    if (bill.customer_name) doc.text(`Customer: ${bill.customer_name}`);
    doc.moveDown(0.8);

    const colX = { name: 40, hsn: 220, qty: 270, rate: 320, taxable: 375, cgst: 430, sgst: 480, total: 530 };
    const headerY = doc.y;
    doc.fontSize(8).fillColor("#000").font("Helvetica-Bold");
    doc.text("Item", colX.name, headerY);
    doc.text("HSN", colX.hsn, headerY);
    doc.text("Qty", colX.qty, headerY);
    doc.text("Rate", colX.rate, headerY);
    doc.text("Taxable", colX.taxable, headerY);
    doc.text("CGST", colX.cgst, headerY);
    doc.text("SGST", colX.sgst, headerY);
    doc.text("Total", colX.total, headerY);
    doc.moveDown(0.4);
    doc.moveTo(40, doc.y).lineTo(560, doc.y).strokeColor("#ccc").stroke();
    doc.font("Helvetica").fontSize(8);

    for (const l of lines) {
      const y = doc.y + 4;
      doc.text(l.product_name, colX.name, y, { width: 175 });
      doc.text(l.hsn_code, colX.hsn, y);
      doc.text(`${l.qty} ${l.unit}`, colX.qty, y, { width: 45 });
      doc.text(`₹${l.unit_price}`, colX.rate, y);
      doc.text(`₹${l.line_subtotal}`, colX.taxable, y);
      doc.text(`₹${l.line_cgst}`, colX.cgst, y);
      doc.text(`₹${l.line_sgst}`, colX.sgst, y);
      doc.text(`₹${l.line_total}`, colX.total, y);
      doc.moveDown(0.9);
    }

    doc.moveTo(40, doc.y).lineTo(560, doc.y).strokeColor("#ccc").stroke();
    doc.moveDown(0.5);
    const totalsX = 420;
    doc.fontSize(9);
    doc.text(`Subtotal:`, totalsX, doc.y, { continued: true }).text(`  ₹${bill.subtotal}`, { align: "right" });
    doc.text(`CGST:`, totalsX, doc.y, { continued: true }).text(`  ₹${bill.cgst}`, { align: "right" });
    doc.text(`SGST:`, totalsX, doc.y, { continued: true }).text(`  ₹${bill.sgst}`, { align: "right" });
    doc.text(`Round off:`, totalsX, doc.y, { continued: true }).text(`  ₹${bill.round_off}`, { align: "right" });
    doc.font("Helvetica-Bold").text(`Grand Total:`, totalsX, doc.y, { continued: true }).text(`  ₹${bill.total}`, { align: "right" });

    doc.moveDown(2);
    doc.font("Helvetica").fontSize(7).fillColor("#888").text("Generated by the Nebula Supermarket Ops Agent.", 40, doc.y);

    doc.end();
    stream.on("finish", resolve);
    stream.on("error", reject);
  });

  return { status: "ok", billId: bill.id, filePath, message: `Invoice for bill #${bill.id} generated.` };
}
